version: "3.7"
services:
    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_DB: fejk
            POSTGRES_NAME: fejk
            POSTGRES_PASSWORD: fejk
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - data:/var/lib/postgresql/data
    app:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        networks:
            - default
        ports:
            - "8124:8124"
volumes:
    data:
    
